import {useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {submitReviewerDecision} from "../api/documents";
import {PageShell} from "../components/PageShell";
import {ClauseCard} from "../components/ClauseCard";
import type {ComplianceReport, ReviewerDecision} from "../types/api";

export function ReportPage(){
 const report=useMemo(()=>JSON.parse(sessionStorage.getItem("compliance-report")??"null")as ComplianceReport|null,[]);
 const [review,setReview]=useState<ReviewerDecision|null>(report?.reviewer_decision??null),[reviewerId,setReviewerId]=useState(""),[note,setNote]=useState(""),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);
 if(!report)return <PageShell><p>No report is available. <Link to="/">Analyze a document</Link>.</p></PageShell>;
 const entities=report.structured_entities?.entities??report.entities?.entities??[];
 const save=async(decision:string)=>{if(!report.report?.report_id){setError("This result has no report identifier.");return;}if(!reviewerId.trim()){setError("Enter your reviewer ID before signing off.");return;}setSaving(true);setError(null);try{setReview(await submitReviewerDecision(report.report.report_id,reviewerId,decision,note));}catch(e){setError(e instanceof Error?e.message:"Could not save decision.");}finally{setSaving(false);}};
 return <PageShell><div className="flex justify-between gap-4"><div><h1 className="text-xl font-semibold">Compliance report</h1><p>Document risk: {report.document_risk.risk_tier??"Unavailable"}</p></div><div className="flex gap-2"><a href={report.report?.download_url} className="border px-3 py-2 text-sm">Download JSON</a><Link to="/" className="border px-3 py-2 text-sm">Analyze another</Link></div></div>
 <section className="mt-6 rounded-md border p-5"><h2 className="font-semibold">Document understanding</h2><p className="mt-1 text-sm">{report.document_understanding?.message??"No visual-analysis result returned."}</p><p className="mt-2 text-sm">Pages: {report.document_understanding?.page_count??"—"}; sequence: {report.document_understanding?.page_sequence_status??"—"}; missing: {(report.document_understanding?.missing_page_numbers??[]).join(", ")||"none detected"}</p><div className="mt-3 space-y-1 text-sm">{report.document_understanding?.pages?.map(page=><p key={page.page_number}>Page {page.page_number}: {page.scan_quality} scan, {page.layout}, signature {page.signature_present?"detected":"not detected"}, type {page.document_type}</p>)}</div></section>
 <section className="mt-4 rounded-md border p-5"><h2 className="font-semibold">Extracted entities and checks</h2><div className="mt-2 text-sm">{entities.length?entities.map((entity,index)=><p key={index}>{entity.entity_type??"Entity"}: {entity.value??JSON.stringify(entity)} {entity.confidence!==undefined?`(${Math.round(entity.confidence*100)}%)`:""}</p>):<p>No structured entities returned.</p>}</div><div className="mt-3 space-y-1 text-sm">{report.deterministic_verification.map(check=><p key={check.rule_id}><b>{check.rule_id}</b> — {check.status}: {check.message}</p>)}</div></section>
 <section className="mt-4 rounded-md border p-5"><h2 className="font-semibold">Human final sign-off</h2>{review?<p className="mt-2 text-sm">{review.decision} by {review.reviewer_id} at {new Date(review.decided_at).toLocaleString()}{review.note?`: ${review.note}`:""}</p>:<><input value={reviewerId} onChange={e=>setReviewerId(e.target.value)} placeholder="Reviewer ID" className="mt-3 w-full border px-3 py-2 text-sm"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional review note" className="mt-2 w-full border px-3 py-2 text-sm"/>{error&&<p className="mt-2 text-sm text-red-700">{error}</p>}<div className="mt-3 flex gap-2"><button disabled={saving} onClick={()=>save("APPROVED")} className="border px-3 py-2 text-sm">Approve</button><button disabled={saving} onClick={()=>save("REJECTED")} className="border px-3 py-2 text-sm">Reject</button><button disabled={saving} onClick={()=>save("ESCALATED")} className="border px-3 py-2 text-sm">Escalate</button></div></>}</section>
 <section className="mt-6 space-y-4"><h2 className="font-semibold">Clause assessment</h2>{report.results.map(x=><ClauseCard key={x.clause_id} clause={x}/>)}</section></PageShell>}
